"""add_time_of_day

Revision ID: 4f2621b0b218
Revises: 87dd597b7dfc
Create Date: 2018-05-26 23:25:02.788852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2621b0b218'
down_revision = '87dd597b7dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('time_of_day', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'time_of_day')
    # ### end Alembic commands ###
