"""users_table

Revision ID: d8d2d88014c2
Revises: 4f2621b0b218
Create Date: 2018-05-28 14:08:05.071865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8d2d88014c2'
down_revision = '4f2621b0b218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=3000), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=3000), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('meal', 'time_of_day',
               existing_type=mysql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', ''),
               nullable=True,
               existing_server_default=sa.text("'DINNER'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'time_of_day',
               existing_type=mysql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', ''),
               nullable=False,
               existing_server_default=sa.text("'DINNER'"))
    op.drop_table('user')
    # ### end Alembic commands ###
