# Generated by Django 2.2.6 on 2019-10-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField(default=0)),
                ('current_quantity', models.IntegerField(default=0)),
                ('time_of_day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MealRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=20)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('meals', models.ManyToManyField(through='mealservice.MealRequirement', to='mealservice.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.Patient')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.Requirement')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.Meal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='meals',
            field=models.ManyToManyField(through='mealservice.PatientMeal', to='mealservice.Meal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='requirements',
            field=models.ManyToManyField(through='mealservice.PatientRequirement', to='mealservice.Requirement'),
        ),
        migrations.AddField(
            model_name='mealrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.Requirement'),
        ),
    ]
