# Generated by Django 2.2.6 on 2019-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('ALLERGEN', 'Allergy'), ('DIETARY_POSITIVE', 'Positive'), ('DIETARY_NEGATIVE', 'Negative')], max_length=20),
        ),
    ]
