# Generated by Django 2.2.6 on 2019-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealservice', '0002_auto_20191004_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time_of_day',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='meals',
            field=models.ManyToManyField(related_name='patients', through='mealservice.PatientMeal', to='mealservice.Meal'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='requirements',
            field=models.ManyToManyField(related_name='patients', through='mealservice.PatientRequirement', to='mealservice.Requirement'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='meals',
            field=models.ManyToManyField(related_name='requirements', through='mealservice.MealRequirement', to='mealservice.Meal'),
        ),
    ]
