# Generated by Django 2.2.6 on 2019-10-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealservice', '0003_auto_20191004_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_requirements',
            field=models.ManyToManyField(related_name='meal', through='mealservice.MealRequirement', to='mealservice.Requirement'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_meals',
            field=models.ManyToManyField(related_name='patient', through='mealservice.PatientMeal', to='mealservice.Meal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_requirements',
            field=models.ManyToManyField(related_name='patient', through='mealservice.PatientRequirement', to='mealservice.Requirement'),
        ),
        migrations.AlterField(
            model_name='mealrequirement',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mealservice.Meal'),
        ),
        migrations.AlterField(
            model_name='mealrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealservice.Requirement'),
        ),
        migrations.AlterField(
            model_name='patientmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='mealservice.Meal'),
        ),
        migrations.AlterField(
            model_name='patientmeal',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealservice.Patient'),
        ),
        migrations.AlterField(
            model_name='patientrequirement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mealservice.Patient'),
        ),
        migrations.AlterField(
            model_name='patientrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='mealservice.Requirement'),
        ),
    ]
