# Generated by Django 2.2.6 on 2019-10-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealservice', '0004_auto_20191004_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='time_of_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.MealTime'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealservice.RequirementType'),
        ),
    ]
