# Generated by Django 2.2.6 on 2019-10-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealservice', '0005_auto_20191018_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementtype',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], default='red', max_length=10),
            preserve_default=False,
        ),
    ]
