# Generated by Django 2.2.6 on 2019-10-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealservice', '0006_requirementtype_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequirement',
            name='scale',
            field=models.CharField(choices=[('WHOLE', 'Whole'), ('TRACE', 'Trace')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrequirement',
            name='scale',
            field=models.CharField(choices=[('WHOLE', 'Whole'), ('TRACE', 'Trace')], max_length=20),
        ),
    ]
